# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayuSampleproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.3.1'

  # Pods for PayuSampleproject
pod 'PayUIndia-UPICore'


end
